# Generated by Django 3.1.1 on 2020-09-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_login', models.CharField(max_length=200, verbose_name='Логин пользователя')),
                ('human_mail', models.CharField(max_length=250, verbose_name='Почта пользователя')),
                ('human_password', models.TextField(verbose_name='Пароль пользователя')),
            ],
        ),
    ]
